"""empty message

Revision ID: eaa4620f1a3a
Revises: 88e3222f86ce
Create Date: 2020-10-12 09:30:22.469796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa4620f1a3a'
down_revision = '88e3222f86ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id', 'address')
    )
    op.create_foreign_key(None, 'artist_image_links', 'artists', ['artist_id'], ['id'])
    op.drop_column('artists', 'image_link')
    op.drop_column('shows', 'image_link')
    op.create_foreign_key(None, 'venue_image_links', 'venues', ['venue_id'], ['id'])
    op.alter_column('venues', 'seeking_talent_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('venues', 'image_link')
    op.drop_column('venues', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('venues', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('venues', 'seeking_talent_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_constraint(None, 'venue_image_links', type_='foreignkey')
    op.add_column('shows', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artist_image_links', type_='foreignkey')
    op.drop_table('addresses')
    # ### end Alembic commands ###
